### ISSUE TITLE
There is a problem when train the datasets

### ISSUE THREAD

**Issue by loulan-D** [AKSHAYUBHAT/EAST#3]
There is no problem when 1000 examples are provided .
but when i use 5000 examples to train there is a error:

Traceback (most recent call last):
File "/home/ubuntu/desktop/EAST-train-5.2/EAST-train-5.1/east/icdar.py", line 603, in generator
h, w, _ = im.shape
AttributeError: 'NoneType' object has no attribute 'shape'

I want to know the reason. thanks

**Comment by AKSHAYUBHAT** [comment]
Hey this is a fork with PY2.7 compatibility you should ask this on original repo

https://github.com/argman/EAST
